# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: Action Cats
      uses: jonico/action-cats@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  second:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Output strings
        env:
          foo: ${{needs.build.output.foo}}
          bar: ${{needs.build.output.bar}}
        run: echo $foo && echo $bar
    
